name: Builder
on: [push, pull_request]
jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        name: [macOS, iOS, tvOS, macOS(SwiftPM)]
        include:
          - name: macOS
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS'
            enable_codecov: true
          - name: iOS
            use_xcodebuild: true
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - name: tvOS
            use_xcodebuild: true
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
          - name: macOS(SwiftPM)
            use_xcodebuild: false
    env:
      use_xcodebuild: ${{ matrix.use_xcodebuild }}
      schemes: SwiftJS
      sdk: ${{ matrix.sdk }}
      destination: ${{ matrix.destination }}
      enable_codecov: ${{ matrix.enable_codecov }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.enable_codecov }}
  ubuntu_swift_latest:
    name: latest-${{ matrix.image }}
    container: 
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [xenial, bionic, focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: apt-get update && apt-get install -y libjavascriptcoregtk-4.0-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  linux_swift_latest:
    name: latest-${{ matrix.image }}
    container: 
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [centos8, amazonlinux2]
        include:
          - image: centos8
            jsc: webkit2gtk3-jsc-devel
          - image: amazonlinux2
            jsc: webkitgtk4-jsc-devel
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: yum update -y && yum install -y ${{ matrix.jsc }}
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  ubuntu_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        image: [nightly-xenial, nightly-bionic, nightly-focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: apt-get update && apt-get install -y libjavascriptcoregtk-4.0-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  linux_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        image: [nightly-centos8, nightly-amazonlinux2]
        include:
          - image: nightly-centos8
            jsc: webkit2gtk3-jsc-devel
          - image: nightly-amazonlinux2
            jsc: webkitgtk4-jsc-devel
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: yum update -y && yum install -y ${{ matrix.jsc }}
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
