name: Builder
on: [push, pull_request]
jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        name: [macOS, iOS, tvOS, macOS(SwiftPM)]
        include:
          - name: macOS
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS'
            enable_codecov: true
          - name: iOS
            use_xcodebuild: true
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - name: tvOS
            use_xcodebuild: true
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
          - name: macOS(SwiftPM)
            use_xcodebuild: false
    env:
      use_xcodebuild: ${{ matrix.use_xcodebuild }}
      schemes: SwiftJS
      sdk: ${{ matrix.sdk }}
      destination: ${{ matrix.destination }}
      enable_codecov: ${{ matrix.enable_codecov }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
    - uses: codecov/codecov-action@v2
      if: ${{ matrix.enable_codecov }}
  ubuntu_swift:
    name: ${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swift:${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 5.10]
        distro: [xenial, bionic, focal, jammy]
        exclude:
          - swift_version: 5.9
            distro: bionic
          - swift_version: 5.10
            distro: bionic
          - swift_version: 5.6
            distro: xenial
          - swift_version: 5.7
            distro: xenial
          - swift_version: 5.8
            distro: xenial
          - swift_version: 5.9
            distro: xenial
          - swift_version: 5.10
            distro: xenial
          - swift_version: 5.3
            distro: jammy
          - swift_version: 5.4
            distro: jammy
          - swift_version: 5.5
            distro: jammy
          - swift_version: 5.6
            distro: jammy
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: apt-get update && apt-get install -y libjavascriptcoregtk-4.0-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  ubuntu_swift_nightly:
    name: nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swiftlang/swift:nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        swift_version: [main]
        distro: [focal, jammy]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: apt-get update && apt-get install -y libjavascriptcoregtk-4.0-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
